name: my_precious
description: A home stuff organizer.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: none # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2025.1.2+105
pcVersionAlias: &pcVersion 2025.1.2.105
environment:
  sdk: '>=3.3.2 <4.0.0'
  flutter: ">=1.17.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  domain:
    path: local_plugins/domain

  #This is a simple Service Locator
  get_it: 7.7.0
  
  #This package offers a set of mixin types that makes the binding of data that is stored within GetIt really easy.
  get_it_mixin: 4.2.2

  uuid: 4.5.1
  
  # Default tooltip is break the scroll animation
  just_the_tooltip: 0.0.12

  data:
    path: local_plugins/data

  # Next part of code is generated. Do not edit!
  #DYNAMIC_DEP_PART_START
  store_package:
    path: local_plugins/store/g_android/pack
  #DYNAMIC_DEP_PART_END
  
  device_orientation: 
    git:
        url: https://gitlab.com/mi3van/mi-device-orientation.git
        ref: master
        
dev_dependencies:
  flutter_test:
    sdk: flutter
      
  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: 5.0.0

  # Windows installer builder
  msix: 3.16.8

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  generate: true
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/img_user_avatar.webp
    - assets/images/flutter_logo_grey.webp
    - assets/images/snowflake.webp
    - assets/icons/logo_gdrive.webp

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto-Italic.ttf
          weight: 400
          style: italic
          
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500

        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700

  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

# Config for windows-version build
msix_config:
  display_name: My Precious
  publisher_display_name: Mi3van
  identity_name: com.mi3van.my-precious
  capabilities: internetClient
  msix_version: *pcVersion
  logo_path: ./web/icons/Icon-192.png
# store: true
  app_installer:
    publish_folder_path: D:\Projects\Home\Flutter\My_Precious\windows\build