import 'package:flutter/material.dart';

const TextTheme robotoMyTextTheme = TextTheme(
  displayLarge: TextStyle(
    debugLabel: 'robotoMyTextTheme displayLarge',
    fontFamily: 'Roboto',
    fontWeight: FontWeight.w400,
    fontSize: 57,
    height: 1.123,
    letterSpacing: -0.25,
  ),
  displayMedium: TextStyle(
    debugLabel: 'robotoMyTextTheme displayMedium',
    fontFamily: 'Roboto',
    fontWeight: FontWeight.w400,
    fontSize: 45,
    height: 1.155,
    letterSpacing: 0,
  ),
  displaySmall: TextStyle(
    debugLabel: 'robotoMyTextTheme displaySmall',
    fontFamily: 'Roboto',
    fontWeight: FontWeight.w400,
    fontSize: 36,
    height: 1.22,
    letterSpacing: 0,
  ),
  headlineLarge: TextStyle(
    debugLabel: 'robotoMyTextTheme headlineLarge',
    fontFamily: 'Roboto',
    fontWeight: FontWeight.w400,
    fontSize: 32,
    height: 1.25,
    letterSpacing: 0,
  ),
  headlineMedium: TextStyle(
    debugLabel: 'robotoMyTextTheme headlineMedium',
    fontFamily: 'Roboto',
    fontWeight: FontWeight.w400,
    fontSize: 28,
    height: 1.286,
    letterSpacing: 0,
  ),
  headlineSmall: TextStyle(
    debugLabel: 'robotoMyTextTheme headlineSmall',
    fontFamily: 'Roboto',
    fontWeight: FontWeight.w400,
    fontSize: 24,
    height: 1.333,
    letterSpacing: 0,
  ),
  titleLarge: TextStyle(
    debugLabel: 'robotoMyTextTheme titleLarge',
    fontFamily: 'Roboto',
    fontWeight: FontWeight.w400,
    fontSize: 22,
    height: 1.27,
    letterSpacing: 0,
  ),
  titleMedium: TextStyle(
    debugLabel: 'robotoMyTextTheme titleMedium',
    fontFamily: 'Roboto',
    fontWeight: FontWeight.w500,
    fontSize: 16,
    height: 1.5,
    letterSpacing: 0.1,
  ),
  titleSmall: TextStyle(
    debugLabel: 'robotoMyTextTheme titleSmall',
    fontFamily: 'Roboto',
    fontWeight: FontWeight.w500,
    fontSize: 14,
    height: 1.429,
    letterSpacing: 0.1,
  ),
  labelLarge: TextStyle(
    debugLabel: 'robotoMyTextTheme labelLarge',
    fontFamily: 'Roboto',
    fontWeight: FontWeight.w500,
    fontSize: 14,
    height: 1.429,
    letterSpacing: 0.1,
  ),
  bodyLarge: TextStyle(
    debugLabel: 'robotoMyTextTheme bodyLarge',
    fontFamily: 'Roboto',
    fontWeight: FontWeight.w400,
    fontSize: 16,
    height: 1.5,
    letterSpacing: 0.5,
  ),
  bodyMedium: TextStyle(
    debugLabel: 'robotoMyTextTheme bodyMedium',
    fontFamily: 'Roboto',
    fontWeight: FontWeight.w400,
    fontSize: 14,
    height: 1.429,
    letterSpacing: 0.25,
  ),
  bodySmall: TextStyle(
    debugLabel: 'robotoMyTextTheme bodySmall',
    fontFamily: 'Roboto',
    fontWeight: FontWeight.w400,
    fontSize: 12,
    height: 1.333,
    letterSpacing: 0.4,
  ),
  labelMedium: TextStyle(
    debugLabel: 'robotoMyTextTheme labelMedium',
    fontFamily: 'Roboto',
    fontWeight: FontWeight.w500,
    fontSize: 12,
    height: 1.333,
    letterSpacing: 0.5,
  ),
  labelSmall: TextStyle(
    debugLabel: 'robotoMyTextTheme labelSmall',
    fontFamily: 'Roboto',
    fontWeight: FontWeight.w500,
    fontSize: 11,
    height: 1.455,
    letterSpacing: 0.5,
  ),
);
